---
name: Format

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch: {}

jobs:
  commit:
    name: Format code
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_committer_name: mikewuu
          git_committer_email: hello@mikewu.dev
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Setup
        uses: ./.github/actions/setup
      - name: Format
        run: npm run format
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        if: always()
        with:
          commit_message: 'ci: Format code'
          commit_user_name: mikewuu
          commit_user_email: hello@mikewu.dev
          commit_author: mikewuu <hello@mikewu.dev>
