---
name: Semantic Release

run-name: Semantic Release from ${{ github.ref_name }}

on:
  push:
    branches:
      - 'main'
      - 'next'
      - 'next-major'
      - 'beta'
      - 'alpha'
      - '*.x'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  semantic:
    name: Determine version
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      new_release_published: ${{ steps.release.outputs.new_release_published }}
      new_release_version: ${{ steps.release.outputs.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Semantic release
        id: release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: '^19.0.0'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
